-- Création de la table pour les paramètres globaux (Devise, Nom, Email)
CREATE TABLE IF NOT EXISTS public.app_settings (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    currency_code text default 'XOF',
    currency_symbol text default 'FCFA',
    app_name text default 'BRICK GO',
    support_email text default 'contact@brickgo.com'
);

-- Activer la sécurité (RLS)
ALTER TABLE public.app_settings ENABLE ROW LEVEL SECURITY;

-- Politiques : Lecture publique, modification autorisée pour les authentifiés
DROP POLICY IF EXISTS "Public read settings" ON public.app_settings;
CREATE POLICY "Public read settings" ON public.app_settings FOR SELECT USING (true);

DROP POLICY IF EXISTS "Authenticated update settings" ON public.app_settings;
CREATE POLICY "Authenticated update settings" ON public.app_settings FOR UPDATE USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Authenticated insert settings" ON public.app_settings;
CREATE POLICY "Authenticated insert settings" ON public.app_settings FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Insérer la configuration par défaut (FCFA / BRICK GO)
INSERT INTO public.app_settings (id, currency_code, currency_symbol, app_name, support_email)
VALUES (1, 'XOF', 'FCFA', 'BRICK GO', 'contact@brickgo.com')
ON CONFLICT (id) DO UPDATE 
SET 
    currency_code = EXCLUDED.currency_code, 
    currency_symbol = EXCLUDED.currency_symbol,
    app_name = COALESCE(public.app_settings.app_name, EXCLUDED.app_name),
    support_email = COALESCE(public.app_settings.support_email, EXCLUDED.support_email);

-- Permissions
GRANT ALL ON public.app_settings TO anon, authenticated, service_role;
