-- Création de la table pour les paramètres globaux (Devise, etc.)
CREATE TABLE IF NOT EXISTS public.app_settings (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    currency_code text default 'XOF',
    currency_symbol text default 'FCFA'
);

-- Activer la sécurité (RLS)
ALTER TABLE public.app_settings ENABLE ROW LEVEL SECURITY;

-- Politiques : Tout le monde peut lire, tout le monde (authentifié) peut modifier pour simplifier l'admin
DROP POLICY IF EXISTS "Public read settings" ON public.app_settings;
CREATE POLICY "Public read settings" ON public.app_settings FOR SELECT USING (true);

DROP POLICY IF EXISTS "Authenticated update settings" ON public.app_settings;
CREATE POLICY "Authenticated update settings" ON public.app_settings FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated insert settings" ON public.app_settings FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Insérer la configuration par défaut (FCFA)
INSERT INTO public.app_settings (id, currency_code, currency_symbol)
VALUES (1, 'XOF', 'FCFA')
ON CONFLICT (id) DO UPDATE 
SET currency_code = 'XOF', currency_symbol = 'FCFA';

-- Permissions
GRANT ALL ON public.app_settings TO anon, authenticated, service_role;
