"use client";

import { useState, useEffect } from "react";
import {
    CreditCard,
    Users,
    Shield,
    Globe,
    Plus,
    Trash2,
    Save,
    Check,
    AlertCircle,
    Copy,
    CheckCircle,
    Loader2,
    X,
    UserCheck,
    UserMinus
} from "lucide-react";

import { supabase } from "@/lib/supabase";

export default function SettingsPage() {
    const [activeTab, setActiveTab] = useState("general");
    const [loading, setLoading] = useState(true);
    const [savingSettings, setSavingSettings] = useState(false);
    const [dbTableMissing, setDbTableMissing] = useState(false);
    const [copied, setCopied] = useState(false);

    // Settings State
    const [appName, setAppName] = useState("BRICK GO");
    const [supportEmail, setSupportEmail] = useState("contact@brickgo.com");
    const [activeCurrency, setActiveCurrency] = useState({ code: "XOF", symbol: "FCFA" });

    // Admins State
    const [admins, setAdmins] = useState<any[]>([]);
    const [loadingAdmins, setLoadingAdmins] = useState(true);
    const [isModalOpen, setIsModalOpen] = useState(false);
    const [creatingAdmin, setCreatingAdmin] = useState(false);

    // Form State for new Admin
    const [formData, setFormData] = useState({
        firstName: '',
        lastName: '',
        email: '',
        phone: '',
        password: '',
        role: 'admin',
        department: 'brick_core'
    });

    const availableCurrencies = [
        { code: "XOF", name: "Franc CFA", symbol: "FCFA" },
        { code: "EUR", name: "Euro", symbol: "€" },
        { code: "USD", name: "US Dollar", symbol: "$" },
    ];

    const sqlScript = `-- Pour configurer la table app_settings, exécutez ce script dans l'éditeur SQL Supabase :
CREATE TABLE IF NOT EXISTS public.app_settings (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    currency_code text default 'XOF',
    currency_symbol text default 'FCFA',
    app_name text default 'BRICK GO',
    support_email text default 'contact@brickgo.com'
);

ALTER TABLE public.app_settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public read settings" ON public.app_settings;
CREATE POLICY "Public read settings" ON public.app_settings FOR SELECT USING (true);

DROP POLICY IF EXISTS "Authenticated update settings" ON public.app_settings;
CREATE POLICY "Authenticated update settings" ON public.app_settings FOR UPDATE USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Authenticated insert settings" ON public.app_settings;
CREATE POLICY "Authenticated insert settings" ON public.app_settings FOR INSERT WITH CHECK (auth.role() = 'authenticated');

INSERT INTO public.app_settings (id, currency_code, currency_symbol, app_name, support_email)
VALUES (1, 'XOF', 'FCFA', 'BRICK GO', 'contact@brickgo.com')
ON CONFLICT (id) DO NOTHING;

GRANT ALL ON public.app_settings TO anon, authenticated, service_role;`;

    useEffect(() => {
        fetchSettings();
        fetchAdmins();

        // Real-time synchronization for admin profiles
        const channel = supabase
            .channel('public:profiles_settings')
            .on('postgres_changes', { event: '*', schema: 'public', table: 'profiles' }, (payload) => {
                console.log('Real-time admin update:', payload);
                fetchAdmins();
            })
            .subscribe();

        return () => {
            supabase.removeChannel(channel);
        };
    }, []);

    const fetchSettings = async () => {
        try {
            setLoading(true);
            const { data, error } = await supabase
                .from('app_settings')
                .select('*')
                .limit(1)
                .maybeSingle();

            if (error) {
                // If code is PGRST205, it means the table public.app_settings does not exist
                if (error.code === 'PGRST205' || error.message?.includes('does not exist')) {
                    setDbTableMissing(true);
                } else {
                    console.error("Error loading app_settings:", error);
                }
            } else if (data) {
                setAppName(data.app_name || "BRICK GO");
                setSupportEmail(data.support_email || "contact@brickgo.com");
                setActiveCurrency({ 
                    code: data.currency_code || "XOF", 
                    symbol: data.currency_symbol || "FCFA" 
                });
                setDbTableMissing(false);
            } else {
                // No rows, table exists. Let's seed row 1 if authenticated
                await seedDefaultSettings();
            }
        } catch (err) {
            console.error(err);
            setDbTableMissing(true);
        } finally {
            setLoading(false);
        }
    };

    const seedDefaultSettings = async () => {
        try {
            const { error } = await supabase
                .from('app_settings')
                .insert([{ id: 1, currency_code: 'XOF', currency_symbol: 'FCFA', app_name: 'BRICK GO', support_email: 'contact@brickgo.com' }]);
            if (!error) {
                setDbTableMissing(false);
            }
        } catch (err) {
            console.error("Failed to seed default settings:", err);
        }
    };

    const fetchAdmins = async () => {
        try {
            setLoadingAdmins(true);
            const { data, error } = await supabase
                .from('profiles')
                .select('*')
                .in('role', ['admin', 'super_admin'])
                .order('created_at', { ascending: false });

            if (error) throw error;
            setAdmins(data || []);
        } catch (err: any) {
            console.error("Error fetching admins:", err);
        } finally {
            setLoadingAdmins(false);
        }
    };

    const handleSaveGeneralSettings = async (e: React.FormEvent) => {
        e.preventDefault();
        if (dbTableMissing) {
            alert("Impossible d'enregistrer : la table 'app_settings' est manquante en base de données. Veuillez exécuter le script SQL ci-dessus.");
            return;
        }

        setSavingSettings(true);
        try {
            const { error } = await supabase
                .from('app_settings')
                .update({ app_name: appName, support_email: supportEmail })
                .eq('id', 1);

            if (error) {
                // Try inserting if not existing
                const { error: insertErr } = await supabase
                    .from('app_settings')
                    .upsert([{ id: 1, app_name: appName, support_email: supportEmail }]);

                if (insertErr) throw insertErr;
            }

            alert("Paramètres généraux enregistrés avec succès !");
        } catch (err: any) {
            console.error(err);
            alert("Erreur lors de l'enregistrement : " + err.message);
        } finally {
            setSavingSettings(false);
        }
    };

    const handleSetCurrency = async (curr: any) => {
        if (dbTableMissing) {
            // Update locally for fallback demonstration
            setActiveCurrency({ code: curr.code, symbol: curr.symbol });
            alert(`[Simulation] Devise changée localement pour : ${curr.name}. Note: La table 'app_settings' est manquante.`);
            return;
        }

        try {
            const { error } = await supabase
                .from('app_settings')
                .update({ currency_code: curr.code, currency_symbol: curr.symbol })
                .eq('id', 1);

            if (error) {
                const { error: insertErr } = await supabase
                    .from('app_settings')
                    .upsert([{ id: 1, currency_code: curr.code, currency_symbol: curr.symbol, app_name: appName, support_email: supportEmail }]);
                if (insertErr) throw insertErr;
            }

            setActiveCurrency({ code: curr.code, symbol: curr.symbol });
            alert(`Devise activée avec succès : ${curr.name} (${curr.symbol})`);
        } catch (err: any) {
            alert('Erreur lors du changement de devise : ' + err.message);
        }
    };

    const handleUpdateAdminStatus = async (id: string, currentStatus: string) => {
        const newStatus = currentStatus === 'active' ? 'inactive' : 'active';
        try {
            const { error } = await supabase
                .from('profiles')
                .update({ status: newStatus })
                .eq('id', id);

            if (error) throw error;
            alert(`Statut de l'administrateur mis à jour (${newStatus === 'active' ? 'Activé' : 'Désactivé'}).`);
            fetchAdmins();
        } catch (err: any) {
            alert("Erreur lors de la mise à jour : " + err.message);
        }
    };

    const handleCreateAdmin = async (e: React.FormEvent) => {
        e.preventDefault();
        setCreatingAdmin(true);

        try {
            const response = await fetch('/api/users', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(formData),
            });

            const data = await response.json();

            if (!response.ok) {
                throw new Error(data.error || 'Erreur lors de la création');
            }

            setIsModalOpen(false);
            setFormData({
                firstName: '',
                lastName: '',
                email: '',
                phone: '',
                password: '',
                role: 'admin',
                department: 'brick_core'
            });
            alert('Administrateur invité et créé avec succès !');
            fetchAdmins();
        } catch (err: any) {
            alert(err.message);
        } finally {
            setCreatingAdmin(false);
        }
    };

    const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
        setFormData({
            ...formData,
            [e.target.name]: e.target.value
        });
    };

    const copyToClipboard = () => {
        navigator.clipboard.writeText(sqlScript);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    const tabs = [
        { id: "general", label: "Général", icon: Globe },
        { id: "currencies", label: "Devises", icon: CreditCard },
        { id: "admins", label: "Administrateurs", icon: Users },
        { id: "security", label: "Sécurité", icon: Shield },
    ];

    return (
        <main className="p-6 lg:p-10 bg-[#F8FAFC]">
            <header className="mb-8 lg:mb-10 text-center lg:text-left">
                <h1 className="text-2xl lg:text-3xl font-black text-[#0F172A] tracking-tight">Paramètres</h1>
                <p className="text-[#64748B] mt-1 text-sm font-medium">Gérez la plateforme globale.</p>
            </header>

            {/* ERROR BANNER IF TABLE IS MISSING */}
            {dbTableMissing && (
                <div className="mb-8 p-6 bg-amber-50 border border-amber-200 rounded-3xl animate-in fade-in slide-in-from-top-4 duration-300">
                    <div className="flex items-start space-x-4">
                        <div className="bg-amber-100 p-3 rounded-2xl text-amber-600 flex-shrink-0">
                            <AlertCircle size={24} />
                        </div>
                        <div className="flex-1 min-w-0">
                            <h3 className="text-lg font-bold text-amber-900">Base de données incomplète</h3>
                            <p className="text-amber-700 text-sm mt-1 leading-relaxed">
                                La table <code className="bg-amber-100 px-1.5 py-0.5 rounded font-mono font-bold text-xs">app_settings</code> stockant la configuration générale et les devises n'existe pas encore sur votre serveur Supabase. L'application utilise temporairement des valeurs par défaut.
                            </p>
                            
                            <div className="mt-4 bg-[#0F172A] rounded-2xl overflow-hidden border border-slate-800">
                                <div className="flex items-center justify-between px-4 py-2 bg-slate-900 border-b border-slate-800">
                                    <span className="text-xs font-mono font-bold text-slate-400">setup_settings_v2.sql</span>
                                    <button 
                                        onClick={copyToClipboard}
                                        className="flex items-center space-x-1.5 px-3 py-1 bg-slate-800 hover:bg-slate-700 active:scale-95 text-xs text-white rounded-lg font-semibold transition-all"
                                    >
                                        {copied ? <Check size={12} className="text-green-400" /> : <Copy size={12} />}
                                        <span>{copied ? "Copié !" : "Copier le script"}</span>
                                    </button>
                                </div>
                                <pre className="p-4 text-xs font-mono text-emerald-400 overflow-x-auto max-h-48 leading-relaxed scrollbar-thin">
                                    {sqlScript}
                                </pre>
                            </div>
                        </div>
                    </div>
                </div>
            )}

            <div className="flex flex-col lg:flex-row gap-6 lg:gap-10 items-start">
                {/* Sidebar Navigation */}
                <div className="w-full lg:w-72 flex-shrink-0">
                    <nav className="flex lg:flex-col overflow-x-auto lg:overflow-visible pb-2 lg:pb-0 space-x-3 lg:space-x-0 lg:space-y-2 scrollbar-hide">
                        {tabs.map((tab) => {
                            const Icon = tab.icon;
                            return (
                                <button
                                    key={tab.id}
                                    onClick={() => setActiveTab(tab.id)}
                                    className={`flex-shrink-0 flex items-center space-x-3 px-5 py-3.5 lg:px-4 lg:py-3 rounded-2xl transition-all duration-200 font-bold text-sm whitespace-nowrap shadow-sm border ${activeTab === tab.id
                                        ? "bg-[#4F46E5] text-white border-[#4F46E5] ring-4 ring-[#4F46E5]/10"
                                        : "bg-white text-[#64748B] border-[#E2E8F0] hover:bg-[#F1F5F9] hover:text-[#1E293B]"
                                        }`}
                                >
                                    <Icon size={18} />
                                    <span>{tab.label}</span>
                                </button>
                            );
                        })}
                    </nav>
                </div>

                {/* Content Area */}
                <div className="flex-1 w-full bg-white rounded-3xl shadow-sm border border-[#E2E8F0] p-6 lg:p-10 min-h-[600px] relative">
                    {loading && activeTab !== "admins" && (
                        <div className="absolute inset-0 bg-white/50 backdrop-blur-[1px] flex items-center justify-center z-10 rounded-3xl">
                            <Loader2 className="w-10 h-10 text-[#4F46E5] animate-spin" />
                        </div>
                    )}

                    {/* GENERAL TAB */}
                    {activeTab === "general" && (
                        <form onSubmit={handleSaveGeneralSettings} className="space-y-8 animate-in fade-in duration-300">
                            <div>
                                <h2 className="text-xl font-bold text-[#0F172A] mb-2">Informations Générales</h2>
                                <p className="text-sm text-[#64748B] mb-6">Configurez les métadonnées de l'application.</p>
                                <div className="grid gap-6 max-w-xl">
                                    <div>
                                        <label className="block text-sm font-bold text-[#64748B] mb-2">Nom de l'application</label>
                                        <input 
                                            type="text" 
                                            value={appName}
                                            onChange={(e) => setAppName(e.target.value)}
                                            required
                                            className="w-full bg-[#F8FAFC] border border-[#E2E8F0] rounded-xl px-4 py-3 text-[#0F172A] font-bold outline-none focus:ring-2 focus:ring-[#4F46E5]/20 focus:border-[#4F46E5] transition-all" 
                                        />
                                    </div>
                                    <div>
                                        <label className="block text-sm font-bold text-[#64748B] mb-2">Email de support</label>
                                        <input 
                                            type="email" 
                                            value={supportEmail}
                                            onChange={(e) => setSupportEmail(e.target.value)}
                                            required
                                            className="w-full bg-[#F8FAFC] border border-[#E2E8F0] rounded-xl px-4 py-3 text-[#0F172A] font-bold outline-none focus:ring-2 focus:ring-[#4F46E5]/20 focus:border-[#4F46E5] transition-all" 
                                        />
                                    </div>
                                </div>
                            </div>
                            <div className="pt-6 border-t border-[#E2E8F0]">
                                <button 
                                    type="submit"
                                    disabled={savingSettings || dbTableMissing}
                                    className="bg-[#4F46E5] hover:bg-[#4338CA] disabled:opacity-50 disabled:cursor-not-allowed text-white px-6 py-3 rounded-xl font-bold shadow-lg shadow-indigo-500/20 flex items-center space-x-2 transition-all"
                                >
                                    {savingSettings ? <Loader2 size={18} className="animate-spin" /> : <Save size={18} />}
                                    <span>{savingSettings ? "Enregistrement..." : "Enregistrer les modifications"}</span>
                                </button>
                            </div>
                        </form>
                    )}

                    {/* CURRENCIES TAB */}
                    {activeTab === "currencies" && (
                        <div className="space-y-6 animate-in fade-in duration-300">
                            <div className="flex justify-between items-center mb-6">
                                <div>
                                    <h2 className="text-xl font-bold text-[#0F172A]">Devises gérées</h2>
                                    <p className="text-sm text-[#64748B] mt-1">La devise active sera utilisée partout sur l'application.</p>
                                </div>
                            </div>

                            <div className="space-y-3 max-w-2xl">
                                {availableCurrencies.map((curr, idx) => {
                                    const isActive = activeCurrency.code === curr.code;
                                    return (
                                        <div key={idx} className={`flex items-center justify-between p-4 rounded-xl border transition-all ${isActive ? "bg-indigo-50 border-indigo-200 ring-1 ring-indigo-200" : "bg-white border-[#E2E8F0]"}`}>
                                            <div className="flex items-center space-x-4">
                                                <div className={`w-10 h-10 rounded-full flex items-center justify-center font-bold shadow-sm border ${isActive ? "bg-indigo-600 text-white border-indigo-600" : "bg-white text-slate-500 border-slate-200"}`}>
                                                    {curr.symbol}
                                                </div>
                                                <div>
                                                    <div className="font-bold text-[#0F172A]">{curr.name}</div>
                                                    <div className="text-xs font-bold text-[#64748B]">{curr.code}</div>
                                                </div>
                                            </div>
                                            <div className="flex items-center space-x-4">
                                                {isActive ? (
                                                    <div className="flex items-center text-indigo-600 font-bold text-sm bg-white px-3 py-1 rounded-full shadow-sm">
                                                        <Check size={14} className="mr-1" /> Active
                                                    </div>
                                                ) : (
                                                    <button
                                                        onClick={() => handleSetCurrency(curr)}
                                                        className="px-4 py-2 bg-white border border-slate-200 rounded-lg text-slate-600 text-sm font-bold hover:bg-indigo-50 hover:text-indigo-600 transition-colors"
                                                    >
                                                        Activer
                                                    </button>
                                                )}
                                            </div>
                                        </div>
                                    );
                                })}
                            </div>
                        </div>
                    )}

                    {/* ADMINS TAB */}
                    {activeTab === "admins" && (
                        <div className="space-y-6 animate-in fade-in duration-300 relative">
                            {loadingAdmins && (
                                <div className="absolute inset-0 bg-white/50 backdrop-blur-[1px] flex items-center justify-center z-10 rounded-3xl">
                                    <Loader2 className="w-10 h-10 text-[#4F46E5] animate-spin" />
                                </div>
                            )}

                            <div className="flex justify-between items-center mb-6">
                                <div>
                                    <h2 className="text-xl font-bold text-[#0F172A]">Gestion des Administrateurs</h2>
                                    <p className="text-sm text-[#64748B]">Gérez les accès et les rôles de votre équipe.</p>
                                </div>
                                <button 
                                    onClick={() => setIsModalOpen(true)}
                                    className="bg-[#4F46E5] hover:bg-[#4338CA] text-white px-4 py-2.5 rounded-xl font-bold text-sm flex items-center space-x-2 transition-all shadow-lg shadow-indigo-500/20 active:scale-95"
                                >
                                    <Plus size={16} />
                                    <span>Inviter un admin</span>
                                </button>
                            </div>

                            <div className="overflow-hidden rounded-xl border border-[#E2E8F0]">
                                <table className="w-full text-left">
                                    <thead className="bg-[#F8FAFC] text-[#64748B] text-xs font-bold uppercase">
                                        <tr>
                                            <th className="px-6 py-4">Utilisateur</th>
                                            <th className="px-6 py-4">Rôle</th>
                                            <th className="px-6 py-4">Statut</th>
                                            <th className="px-6 py-4 text-right">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody className="divide-y divide-[#E2E8F0]">
                                        {admins.map((admin) => (
                                            <tr key={admin.id} className="hover:bg-[#F8FAFC]/50 transition-colors">
                                                <td className="px-6 py-4">
                                                    <div className="flex items-center space-x-3">
                                                        <div className="w-9 h-9 rounded-full bg-indigo-50 text-[#4F46E5] flex items-center justify-center font-bold text-xs uppercase">
                                                            {admin.first_name ? admin.first_name[0] : (admin.email ? admin.email[0] : "A")}
                                                        </div>
                                                        <div>
                                                            <div className="font-bold text-[#0F172A] text-sm">
                                                                {admin.first_name || admin.last_name
                                                                    ? `${admin.first_name || ''} ${admin.last_name || ''}`
                                                                    : "Administrateur"}
                                                            </div>
                                                            <div className="text-xs text-[#64748B]">{admin.email}</div>
                                                        </div>
                                                    </div>
                                                </td>
                                                <td className="px-6 py-4">
                                                    <span className={`px-2.5 py-1 rounded-full text-xs font-bold ${
                                                        admin.role === 'super_admin' ? 'bg-indigo-50 text-indigo-700' : 'bg-slate-50 text-slate-600 border border-slate-200'
                                                    }`}>
                                                        {admin.role === 'super_admin' ? 'Super Admin' : 'Admin'}
                                                    </span>
                                                </td>
                                                <td className="px-6 py-4">
                                                    <span className={`px-2.5 py-1 text-[10px] font-black rounded-full uppercase tracking-wide ${
                                                        admin.status === 'active' ? 'bg-green-100 text-green-700' : 'bg-rose-100 text-rose-700'
                                                    }`}>
                                                        {admin.status === 'active' ? 'Actif' : 'Inactif'}
                                                    </span>
                                                </td>
                                                <td className="px-6 py-4 text-right">
                                                    <button 
                                                        onClick={() => handleUpdateAdminStatus(admin.id, admin.status)}
                                                        className={`transition-colors font-bold text-xs uppercase px-3 py-1.5 rounded-lg border ${
                                                            admin.status === 'active' 
                                                                ? 'text-rose-600 border-rose-200 hover:bg-rose-50 hover:border-rose-300' 
                                                                : 'text-green-600 border-green-200 hover:bg-green-50 hover:border-green-300'
                                                        }`}
                                                    >
                                                        {admin.status === 'active' ? "Désactiver" : "Activer"}
                                                    </button>
                                                </td>
                                            </tr>
                                        ))}
                                        {admins.length === 0 && !loadingAdmins && (
                                            <tr>
                                                <td colSpan={4} className="px-6 py-10 text-center text-[#64748B] font-medium text-sm">
                                                    Aucun administrateur trouvé.
                                                </td>
                                            </tr>
                                        )}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    )}

                    {/* SECURITY TAB */}
                    {activeTab === "security" && (
                        <div className="space-y-6 animate-in fade-in duration-300 max-w-xl">
                            <h2 className="text-xl font-bold text-[#0F172A]">Sécurité globale</h2>
                            <p className="text-sm text-[#64748B]">Gérez les règles de sécurité et l'accès réseau.</p>
                            
                            <div className="bg-amber-50 border border-amber-200 rounded-2xl p-5 flex items-start space-x-3.5">
                                <Shield className="text-amber-600 mt-0.5 flex-shrink-0" size={22} />
                                <div>
                                    <h3 className="font-bold text-amber-900 text-base">Authentification à deux facteurs (2FA)</h3>
                                    <p className="text-sm text-amber-700 mt-1 leading-relaxed">
                                        L'activation obligatoire de la 2FA pour tous les administrateurs et commerciaux est en cours de déploiement technique et sera disponible dans la prochaine mise à jour de la plateforme.
                                    </p>
                                </div>
                            </div>

                            <div className="p-5 border border-slate-200 rounded-2xl space-y-4">
                                <h3 className="font-bold text-[#0F172A]">Règles de mot de passe</h3>
                                <div className="space-y-2.5">
                                    <div className="flex items-center text-sm text-[#475569] font-medium">
                                        <div className="w-1.5 h-1.5 rounded-full bg-[#4F46E5] mr-2"></div>
                                        Longueur minimale de 8 caractères
                                    </div>
                                    <div className="flex items-center text-sm text-[#475569] font-medium">
                                        <div className="w-1.5 h-1.5 rounded-full bg-[#4F46E5] mr-2"></div>
                                        Obligation d'inclure des chiffres et caractères spéciaux
                                    </div>
                                </div>
                            </div>
                        </div>
                    )}
                </div>
            </div>

            {/* Modal d'invitation d'Administrateur */}
            {isModalOpen && (
                <div className="fixed inset-0 bg-black/55 backdrop-blur-sm z-50 flex items-center justify-center p-4 animate-in fade-in duration-200">
                    <div className="bg-white rounded-3xl w-full max-w-md shadow-2xl overflow-hidden transform transition-all scale-100 border border-slate-100 animate-in zoom-in-95 duration-200">
                        <div className="p-6 border-b border-slate-100 flex justify-between items-center bg-[#F8FAFC]">
                            <h3 className="text-lg lg:text-xl font-black text-[#0F172A]">Inviter un admin</h3>
                            <button onClick={() => setIsModalOpen(false)} className="text-gray-400 hover:text-gray-600 transition-colors p-1 rounded-lg hover:bg-slate-100">
                                <X size={20} />
                            </button>
                        </div>

                        <form onSubmit={handleCreateAdmin} className="p-6 space-y-4">
                            <div className="grid grid-cols-2 gap-4">
                                <div>
                                    <label className="block text-xs font-black text-[#64748B] uppercase tracking-wider mb-2">Prénom</label>
                                    <input
                                        type="text"
                                        name="firstName"
                                        required
                                        value={formData.firstName}
                                        onChange={handleInputChange}
                                        className="w-full px-4 py-3 rounded-xl border border-gray-200 focus:border-[#4F46E5] focus:ring-2 focus:ring-[#4F46E5]/20 outline-none transition-all text-sm font-semibold"
                                        placeholder="Ex: Jean"
                                    />
                                </div>
                                <div>
                                    <label className="block text-xs font-black text-[#64748B] uppercase tracking-wider mb-2">Nom</label>
                                    <input
                                        type="text"
                                        name="lastName"
                                        required
                                        value={formData.lastName}
                                        onChange={handleInputChange}
                                        className="w-full px-4 py-3 rounded-xl border border-gray-200 focus:border-[#4F46E5] focus:ring-2 focus:ring-[#4F46E5]/20 outline-none transition-all text-sm font-semibold"
                                        placeholder="Ex: Dupont"
                                    />
                                </div>
                            </div>

                            <div>
                                <label className="block text-xs font-black text-[#64748B] uppercase tracking-wider mb-2">Email</label>
                                <input
                                    type="email"
                                    name="email"
                                    required
                                    value={formData.email}
                                    onChange={handleInputChange}
                                    className="w-full px-4 py-3 rounded-xl border border-gray-200 focus:border-[#4F46E5] focus:ring-2 focus:ring-[#4F46E5]/20 outline-none transition-all text-sm font-semibold"
                                    placeholder="jean.dupont@brickgo.com"
                                />
                            </div>

                            <div>
                                <label className="block text-xs font-black text-[#64748B] uppercase tracking-wider mb-2">Téléphone</label>
                                <input
                                    type="tel"
                                    name="phone"
                                    value={formData.phone}
                                    onChange={handleInputChange}
                                    className="w-full px-4 py-3 rounded-xl border border-gray-200 focus:border-[#4F46E5] focus:ring-2 focus:ring-[#4F46E5]/20 outline-none transition-all text-sm font-semibold"
                                    placeholder="Ex: 06 12 34 56 78"
                                />
                            </div>

                            <div className="grid grid-cols-2 gap-4">
                                <div>
                                    <label className="block text-xs font-black text-[#64748B] uppercase tracking-wider mb-2">Rôle</label>
                                    <select
                                        name="role"
                                        value={formData.role}
                                        onChange={handleInputChange}
                                        className="w-full px-4 py-3 rounded-xl border border-gray-200 focus:border-[#4F46E5] focus:ring-2 focus:ring-[#4F46E5]/20 outline-none transition-all text-sm font-bold text-[#4F46E5] bg-white cursor-pointer"
                                    >
                                        <option value="admin">Admin</option>
                                        <option value="super_admin">Super Admin</option>
                                    </select>
                                </div>
                                <div>
                                    <label className="block text-xs font-black text-[#64748B] uppercase tracking-wider mb-2">Département</label>
                                    <select
                                        name="department"
                                        value={formData.department}
                                        onChange={handleInputChange}
                                        className="w-full px-4 py-3 rounded-xl border border-gray-200 focus:border-[#4F46E5] focus:ring-2 focus:ring-[#4F46E5]/20 outline-none transition-all text-sm font-bold bg-white cursor-pointer"
                                    >
                                        <option value="brick_core">Brick Core</option>
                                        <option value="brick_food">Brick Food 🍔</option>
                                    </select>
                                </div>
                            </div>

                            <div>
                                <label className="block text-xs font-black text-[#64748B] uppercase tracking-wider mb-2">Mot de passe temporaire</label>
                                <input
                                    type="text"
                                    name="password"
                                    required
                                    minLength={6}
                                    value={formData.password}
                                    onChange={handleInputChange}
                                    className="w-full px-4 py-3 rounded-xl border border-gray-200 focus:border-[#4F46E5] focus:ring-2 focus:ring-[#4F46E5]/20 outline-none transition-all text-sm font-bold bg-[#F8FAFC]"
                                    placeholder="Minimum 6 caractères"
                                />
                            </div>

                            <button
                                type="submit"
                                disabled={creatingAdmin}
                                className="w-full bg-[#4F46E5] hover:bg-[#4338CA] text-white font-bold py-4 rounded-xl shadow-lg shadow-indigo-500/20 flex items-center justify-center space-x-2 transition-all active:scale-95 disabled:opacity-75 disabled:cursor-not-allowed mt-6"
                            >
                                {creatingAdmin ? (
                                    <Loader2 className="animate-spin" />
                                ) : (
                                    <>
                                        <CheckCircle size={18} />
                                        <span>Créer le compte admin</span>
                                    </>
                                )}
                            </button>
                        </form>
                    </div>
                </div>
            )}
        </main>
    );
}
